export enum FieldType {
    Switch = 'switch-field',
    Line = 'line-field',
    Group = 'group-layout',
    Paper = 'paper-layout',
    Outline = 'outline-layout',
    Expansion= 'expansion-layout',
    Radio = 'radio-field',
    Checkbox = 'checkbox-field',
    Text = 'text-field',
    Date = 'date-field',
    Progress = 'progress-field',
    Component = 'component-field',
    Slider = 'slider-field',
    Combo = 'combo-field',
    Items = 'items-field',
    Rating = 'rating-field',
    Typography = 'typography-field',
    Fragment = 'fragment-layout',
    Div = 'div-layout',
    Tabs = 'tabs-layout',
    Hero = 'hero-layout',
    Center = 'center-layout',
    Stretch = 'stretch-layout',
    Condition = 'condition-layout',
};

export default FieldType;
