export enum FieldType {
    Switch = 'switch',
    Line = 'line',
    Group = 'group',
    Paper = 'paper',
    Outline = 'outline',
    Expansion= 'expansion',
    Radio = 'radio',
    Checkbox = 'checkbox',
    Text = 'text',
    Progress = 'progress',
    Component = 'component',
    Slider = 'slider',
    Combo = 'combo',
    Items = 'items',
    Rating = 'rating',
    Typography = 'typography',
    Fragment = 'fragment',
    Div = 'div',
    Hero = 'hero',
    Center = 'center',
    Stretch = 'stretch',
};

export default FieldType;
